### ISSUE TITLE
Multiple I2C slaves?

### ISSUE THREAD

**Issue by pennybuster** [jaroslavs/REXduino#1]
Does it have support for multiple I2C Arduino slaves? Would I2C be fast enough for most projects even if it's not deterministic? Thanks

**Comment by jaroslavs** [comment]
REXduino uses USB for communication between the master and slave (Arduino), not I2C. Using multiple Arduinos at the same time is possible.

As for the speed, what are your requirements?

**Comment by pennybuster** [comment]
Just comparing Codesys3 to Rex Controls for Raspberry Pi. Both look good.
Will OSCAT (oscat.de) library be available for Rex?

**Comment by jaroslavs** [comment]
That's a question you should ask at support@rexcontrols.com.
